name: Check Build

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: eventjet/checks-7.4:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Composer Cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.COMPOSER_CACHE }}
            vendor
          key: ${{ runner.os }}-composer

      - name: Install dependencies
        run: |
          composer update --no-progress --no-interaction > /dev/null

      - name: Static analysis
        run: |
          composer check-deps
          composer cs-check
          composer phpstan -- --no-progress

      - name: Infection coverage of added files
        if: env.GIT_ADDED_FILES != '' && !contains(github.event.pull_request.labels.*.name, 'skip-infection-diff')
        run: |
          vendor/bin/infection \
            --git-diff-base=origin/$GITHUB_BASE_REF \
            --git-diff-filter=A \
            --logger-github \
            --min-msi=100 \
            --min-covered-msi=100

      - name: Tests
        run: |
          vendor/bin/phpunit --coverage-clover=coverage.xml --stop-on-failure
          composer run --timeout=0 infection

      - name: Save Infection result
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: infection-log.txt
          path: infection-log.txt

      - name: Monitor coverage
        if: github.event_name == 'pull_request'
        uses: slavcodev/coverage-monitor-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clover_file: "coverage.xml"
          threshold_alert: 100
          threshold_warning: 100
